# Generated by Django 3.0.3 on 2020-04-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdse',
            name='indicesA',
            field=models.TextField(default=0, help_text='einsum index string for entropy calculation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdse',
            name='nA',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of qubits in partition A'),
            preserve_default=False,
        ),
    ]
