# Generated by Django 3.0.3 on 2020-04-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdse',
            name='test',
        ),
    ]
