# Generated by Django 3.0.3 on 2020-04-25 06:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0002_remove_tdse_test'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tdse',
            name='unique_tdse',
        ),
        migrations.RemoveField(
            model_name='tdse',
            name='indicesA',
        ),
        migrations.RemoveField(
            model_name='tdse',
            name='nA',
        ),
        migrations.AddField(
            model_name='tdse',
            name='entropy_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'nA': 4}, help_text='Entropy parameters: nA (number of qubits in partition A), indicesA (einsum index notation), reg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdse',
            name='entropy_params_hash',
            field=models.TextField(default='asdf', help_text='md5 hash for entropy parameters'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdse',
            name='wave',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Wavefunction: type (mixed or pure), temp, initial wavefunction (True or transverse)'),
        ),
        migrations.AddConstraint(
            model_name='tdse',
            constraint=models.UniqueConstraint(fields=('tag', 'graph', 'penalty', 'ising_hash', 'offset_hash', 'solver_hash', 'wave_hash', 'entropy_params_hash'), name='unique_tdse'),
        ),
    ]
