# Generated by Django 3.0.3 on 2020-04-22 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0003_auto_20200422_0647'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tdseresult',
            name='unique_tdseresult',
        ),
        migrations.AddField(
            model_name='tdseresult',
            name='tdse',
            field=models.ForeignKey(default=0, help_text='Foreign Key to `Tdse`', on_delete=django.db.models.deletion.CASCADE, to='tdse.Tdse'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tdseresult',
            constraint=models.UniqueConstraint(fields=('tdse', 'nA', 'indicesA'), name='unique_tdseresult'),
        ),
    ]
