# Generated by Django 3.0.3 on 2020-04-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0003_auto_20200425_0637'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tdse',
            name='unique_tdse',
        ),
        migrations.RemoveField(
            model_name='tdse',
            name='penalty',
        ),
        migrations.AddConstraint(
            model_name='tdse',
            constraint=models.UniqueConstraint(fields=('tag', 'graph', 'ising_hash', 'offset_hash', 'solver_hash', 'wave_hash', 'entropy_params_hash'), name='unique_tdse'),
        ),
    ]
