# Generated by Django 3.0.3 on 2020-04-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0004_auto_20200426_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdse',
            name='instance',
            field=models.FileField(help_text='save instance of class', upload_to='tdse/'),
        ),
    ]
