# Generated by Django 3.0.3 on 2020-04-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0005_auto_20200427_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdse',
            name='solution',
            field=models.FileField(default='asdf', help_text='save pickled solution', upload_to='solution/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdse',
            name='instance',
            field=models.FileField(help_text='save pickled instance of class', upload_to='instance/'),
        ),
    ]
