# Generated by Django 3.0.3 on 2020-04-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0006_auto_20200427_0709'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tdse',
            name='unique_tdse',
        ),
        migrations.RemoveField(
            model_name='tdse',
            name='entropy',
        ),
        migrations.RemoveField(
            model_name='tdse',
            name='entropy_params',
        ),
        migrations.RemoveField(
            model_name='tdse',
            name='entropy_params_hash',
        ),
        migrations.AddConstraint(
            model_name='tdse',
            constraint=models.UniqueConstraint(fields=('tag', 'graph', 'ising_hash', 'offset_hash', 'solver_hash', 'wave_hash'), name='unique_tdse'),
        ),
    ]
