# Generated by Django 3.0.3 on 2020-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0006_auto_20200422_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdse',
            name='entropy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tdse',
            name='prob',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tdse',
            name='time',
            field=models.FloatField(),
        ),
    ]
