# Generated by Django 3.0.3 on 2020-05-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0007_auto_20200428_0352'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tdse',
            name='unique_tdse',
        ),
        migrations.AddField(
            model_name='tdse',
            name='gamma',
            field=models.FloatField(default=1, help_text='Inverse decoherence time in Ghz'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tdse',
            constraint=models.UniqueConstraint(fields=('tag', 'graph', 'ising_hash', 'offset_hash', 'solver_hash', 'wave_hash', 'gamma'), name='unique_tdse'),
        ),
    ]
