# Generated by Django 3.0.3 on 2020-04-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0007_auto_20200422_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdse',
            name='entropy',
        ),
        migrations.RemoveField(
            model_name='tdse',
            name='indicesA',
        ),
        migrations.RemoveField(
            model_name='tdse',
            name='nA',
        ),
        migrations.RemoveField(
            model_name='tdse',
            name='prob',
        ),
        migrations.RemoveField(
            model_name='tdse',
            name='time',
        ),
    ]
