# Generated by Django 3.0.3 on 2020-05-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0008_auto_20200502_0749'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tdse',
            name='unique_tdse',
        ),
        migrations.RemoveField(
            model_name='tdse',
            name='gamma',
        ),
        migrations.AddConstraint(
            model_name='tdse',
            constraint=models.UniqueConstraint(fields=('tag', 'graph', 'ising_hash', 'offset_hash', 'solver_hash', 'wave_hash'), name='unique_tdse'),
        ),
    ]
