# Generated by Django 3.0.3 on 2020-04-22 07:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0008_auto_20200422_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdse',
            name='entropy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0], help_text='von Neumann entropy vs. time', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdse',
            name='indicesA',
            field=models.TextField(default='abcdef', help_text='einsum index string for entropy calculation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdse',
            name='nA',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of qubits in partition A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdse',
            name='prob',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0], help_text='Ising ground state probability vs. time', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdse',
            name='time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0], help_text='Normalized time array for evolution', size=None),
            preserve_default=False,
        ),
    ]
