# Generated by Django 3.1.2 on 2020-10-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdse', '0010_auto_20201013_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdse',
            name='ising',
            field=models.JSONField(help_text='Ising parameters: Jij, hi, c, energyscale'),
        ),
        migrations.AlterField(
            model_name='tdse',
            name='offset',
            field=models.JSONField(help_text='Offset parameters: normalized time, offset, hi_for_offset, offset_min, offset_range, fill_value, anneal_curve'),
        ),
        migrations.AlterField(
            model_name='tdse',
            name='solver',
            field=models.JSONField(help_text='Solver parameters: method, rtol, atol'),
        ),
        migrations.AlterField(
            model_name='tdse',
            name='wave',
            field=models.JSONField(help_text='Wavefunction: type (mixed or pure), temp, initial wavefunction (True or transverse)'),
        ),
    ]
