# Generated by Django 3.0.3 on 2020-02-18 03:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.TextField(help_text='Tag for graph type (e.g. Hamming(n,m) or K(n,m))')),
                ('total_vertices', models.PositiveSmallIntegerField(help_text='Total number of vertices in graph')),
                ('total_edges', models.PositiveSmallIntegerField(help_text='Total number of edges in graph')),
                ('max_edges', models.PositiveSmallIntegerField(help_text='Maximum number of edges per vertex')),
                ('adjacency', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=2), help_text='Sorted adjacency matrix of dimension [N, 2]', size=None)),
                ('adjacency_hash', models.TextField(help_text='md5 hash of adjacency list used for unique constraint')),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Ananymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='graph',
            constraint=models.UniqueConstraint(fields=('adjacency_hash',), name='unique_graph'),
        ),
    ]
