# Generated by Django 3.0.3 on 2020-03-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='graph',
            name='unique_graph',
        ),
        migrations.AddConstraint(
            model_name='graph',
            constraint=models.UniqueConstraint(fields=('adjacency_hash', 'tag'), name='unique_graph'),
        ),
    ]
