# Generated by Django 3.0.3 on 2020-02-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='constraint_satisfaction',
            field=models.BooleanField(default=False, help_text='Are the inequality constraints satisfied by the slacks?'),
            preserve_default=False,
        ),
    ]
