# Generated by Django 3.0.3 on 2020-03-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_constraint_satisfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='chain_break_fraction',
            field=models.FloatField(default=0, help_text='Chain break fraction'),
            preserve_default=False,
        ),
    ]
