version: '3'

services:
    db:
        build:
            context: .
            dockerfile: Dockerfile.postgres
        environment:
            - POSTGRES_DB=qlpdb
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=postgres
