name: Build qlp & qlpdb and load data
on: [push]
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v1
            - name: Build the stack
              run: |
                docker-compose build
                docker-compose run qlpdb python manage.py migrate
